/* module: inline */
(function(){
 const CART_KEY='innov_cart_v1', COUPON_KEY='innov_applied_coupon_v1';
 const $=id=>document.getElementById(id); const money=n=>'S/ '+(Number(n)||0).toFixed(2);
 function read(){try{const a=JSON.parse(sessionStorage.getItem(CART_KEY)||localStorage.getItem(CART_KEY)||'[]');return Array.isArray(a)?a:[]}catch(_){return[]}}
 function write(a){sessionStorage.setItem(CART_KEY,JSON.stringify(a));localStorage.removeItem(CART_KEY);window.dispatchEvent(new Event('innov-cart-change'))}
 function normalize(x){return {id:String(x.id||x.plan_id||x.product_id||crypto.randomUUID()),nombre:String(x.nombre||x.name||'Producto'),precio:Number(x.precio||x.price||0),imagen:String(x.imagen||x.image||''),qty:Math.max(1,Math.floor(Number(x.qty||1))),source:x.source||'unknown',product_id:x.product_id||null,plan_id:x.plan_id||null,plan_name:x.plan_name||null,stock_control:x.stock_control||null,meta:x.meta||{}}}
 function saveCoupon(){const code=$('coupon').value.trim().toUpperCase();if(!code){sessionStorage.removeItem(COUPON_KEY);$('couponMsg').textContent='Cupón eliminado. Puedes continuar sin cupón.';return}sessionStorage.setItem(COUPON_KEY,JSON.stringify({code}));$('couponMsg').textContent='Cupón '+code+' guardado. Se validará al generar el pedido.'}
 function render(){let rows=read().map(normalize);write(rows);const host=$('items');const count=rows.reduce((n,x)=>n+x.qty,0);document.querySelectorAll('[data-innov-cart-count]').forEach(e=>e.textContent=String(count));if(!rows.length){host.innerHTML='<div class="empty"><b>Tu carrito está vacío</b>Agrega un producto desde la tienda.</div>';$('checkout').style.pointerEvents='none';$('checkout').style.opacity='.5'}else{$('checkout').style.pointerEvents='';$('checkout').style.opacity='';host.innerHTML=rows.map((x,i)=>`<article class="item"><img class="thumb" src="${escapeHtml(x.imagen||'assets/img/product-placeholder.svg')}" alt=""><div><div class="name">${escapeHtml(x.nombre)}</div><div class="meta">${x.plan_name?escapeHtml(x.plan_name)+' · ':''}${x.plan_id?'Plan validable en servidor':'Catálogo'}</div><div class="qty"><button type="button" data-dec="${i}" aria-label="Reducir">−</button><b>${x.qty}</b><button type="button" data-inc="${i}" aria-label="Aumentar">+</button><button class="remove" type="button" data-del="${i}">Quitar</button></div></div><div class="price">${money(x.precio*x.qty)}</div></article>`).join('')}
 const sub=rows.reduce((n,x)=>n+x.precio*x.qty,0);$('subtotal').textContent=money(sub);$('total').textContent=money(sub);
 host.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>{rows[+b.dataset.inc].qty++;write(rows);render()});host.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>{const x=rows[+b.dataset.dec];x.qty=Math.max(1,x.qty-1);write(rows);render()});host.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{rows.splice(+b.dataset.del,1);write(rows);render()});}
 function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 try{const saved=JSON.parse(sessionStorage.getItem(COUPON_KEY)||'null');if(saved&&saved.code)$('coupon').value=saved.code}catch(_){ }
 $('saveCoupon').onclick=saveCoupon;$('coupon').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();saveCoupon()}});render();
})();
