(function(){
'use strict';
var THEME_KEY='innov_theme', SOURCE_KEY='innov_theme_source';
var query=window.matchMedia?window.matchMedia('(prefers-color-scheme: dark)'):null;
function valid(v){return v==='dark'||v==='light'}
function manual(){try{var v=localStorage.getItem(THEME_KEY),s=localStorage.getItem(SOURCE_KEY);return (s==='manual'||(!s&&valid(v)))&&valid(v)?v:null}catch(_){return null}}
function system(){return query&&query.matches?'dark':'light'}
function update(){var b=document.getElementById('innovThemeToggle'),t=document.documentElement.dataset.theme==='dark'?'dark':'light';if(b){b.classList.toggle('is-dark',t==='dark');b.setAttribute('aria-label',t==='dark'?'Cambiar a modo claro':'Cambiar a modo oscuro');b.setAttribute('title',t==='dark'?'Cambiar a modo claro':'Cambiar a modo oscuro')}var m=document.querySelector('meta[name="theme-color"]');if(m)m.content=t==='dark'?'#0b1320':'#121c2b'}
function apply(t,source){t=t==='dark'?'dark':'light';document.documentElement.dataset.theme=t;document.documentElement.dataset.themeSource=source==='manual'?'manual':'system';document.documentElement.style.colorScheme=t;update()}
function toggle(){var n=document.documentElement.dataset.theme==='dark'?'light':'dark';try{localStorage.setItem(THEME_KEY,n);localStorage.setItem(SOURCE_KEY,'manual')}catch(_){}apply(n,'manual')}
function mountTheme(){if(document.getElementById('innovThemeToggle'))return;var nav=document.querySelector('.innov-safe-nav');if(!nav)return;var b=document.createElement('button');b.type='button';b.id='innovThemeToggle';b.className='innov-theme-toggle';b.innerHTML='<i class="fas fa-moon theme-icon-moon" aria-hidden="true"></i><i class="fas fa-sun theme-icon-sun" aria-hidden="true"></i><span class="sr-only">Cambiar tema</span>';b.addEventListener('click',toggle);var cart=nav.querySelector('.innov-safe-cart');if(cart)nav.insertBefore(b,cart);else nav.appendChild(b)}
function mountMenu(){var b=document.getElementById('innovSafeMenu'),h=document.getElementById('innovSafeHeader');if(!b||!h||b.dataset.bound)return;var nav=h.querySelector('.innov-safe-links');if(nav&&!nav.querySelector('.innov-safe-mobile-socials')){var socials=document.createElement('div');socials.className='innov-safe-mobile-socials';socials.innerHTML='<a href="https://www.facebook.com/profile.php?id=61585560703359" target="_blank" rel="noopener" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a><a href="https://www.instagram.com/innov_iaa/" target="_blank" rel="noopener" aria-label="Instagram"><i class="fab fa-instagram"></i></a><a href="https://www.tiktok.com/@innoovia" target="_blank" rel="noopener" aria-label="TikTok"><i class="fab fa-tiktok"></i></a>';nav.appendChild(socials);nav.querySelectorAll('a').forEach(function(a){a.addEventListener('click',function(){h.classList.remove('is-open');b.setAttribute('aria-expanded','false')})})}b.dataset.bound='1';b.addEventListener('click',function(){var on=h.classList.toggle('is-open');b.setAttribute('aria-expanded',on?'true':'false')})}
function cartRows(){try{var raw=sessionStorage.getItem('innov_cart_v1')||localStorage.getItem('innov_cart_v1')||'[]',a=JSON.parse(raw);return Array.isArray(a)?a:[]}catch(_){return[]}}
function syncCart(){var n=cartRows().reduce(function(s,x){return s+Math.max(1,Number(x&&x.qty||1))},0);document.querySelectorAll('[data-innov-cart-count]').forEach(function(e){e.textContent=String(n)})}
function init(){var m=manual();apply(m||system(),m?'manual':'system');mountTheme();mountMenu();update();syncCart();window.addEventListener('storage',function(e){if(e.key===THEME_KEY||e.key===SOURCE_KEY){var mm=manual();apply(mm||system(),mm?'manual':'system')}if(e.key==='innov_cart_v1')syncCart()});window.addEventListener('innov-cart-change',syncCart);if(query){var q=function(){if(!manual())apply(system(),'system')};if(query.addEventListener)query.addEventListener('change',q);else if(query.addListener)query.addListener(q)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();