(function(){
'use strict';
function byId(id){return document.getElementById(id)}
function syncSearch(source){const target=byId('shopSearchInput');if(!target||!source)return;target.value=source.value||'';target.dispatchEvent(new Event('input',{bubbles:true}));}
function muteModal(){const shell=byId('modalVideo');if(!shell)return;shell.dataset.muted='1';const button=byId('modalSoundBtn');if(button){button.textContent='🔇';button.setAttribute('aria-label','Activar sonido');button.classList.remove('is-sound-on')}try{if(shell._videoEl){shell._videoEl.muted=true;shell._videoEl.volume=0}}catch(_){ }try{if(shell._player&&typeof shell._player.mute==='function'){shell._player.mute();shell._player.setVolume?.(0)}}catch(_){ }try{if(shell._vimeoFrame?.contentWindow){shell._vimeoFrame.contentWindow.postMessage(JSON.stringify({method:'setMuted',value:true}),'*');shell._vimeoFrame.contentWindow.postMessage(JSON.stringify({method:'setVolume',value:0}),'*')}}catch(_){ }}
function openTerms(){const d=byId('innovTermsModal');if(!d)return;try{d.showModal()}catch(_){d.setAttribute('open','')}}
function init(){const mobile=byId('shopMobileSearch'),filters=byId('shopMobileFilters'),old=byId('filtersToggleBtn');if(mobile){mobile.addEventListener('input',()=>syncSearch(mobile));mobile.addEventListener('search',()=>syncSearch(mobile))}if(filters&&old)filters.addEventListener('click',()=>old.click());const form=document.querySelector('.innov-safe-search');if(form){form.addEventListener('submit',e=>{e.preventDefault();const input=form.querySelector('#shopSearchInput');if(input)input.dispatchEvent(new Event('input',{bubbles:true}))})}const terms=byId('modalTermsBtn');if(terms)terms.addEventListener('click',e=>{e.preventDefault();try{window.jQuery?.('#productModal').modal('hide')}catch(_){ }setTimeout(openTerms,180)});document.addEventListener('click',e=>{if(e.target.closest('.btn-detail,.js-title,[data-product-detail],[data-action="detail"]')){setTimeout(muteModal,220);setTimeout(muteModal,760)}},true)}
window.addEventListener('message',event=>{try{const data=typeof event.data==='string'?JSON.parse(event.data):event.data;if(!data||data['x-tiktok-player']!==true||data.type!=='onMute')return;document.querySelectorAll('.modal-product-media .product-video-shell').forEach(shell=>{if(shell._tiktokFrame?.contentWindow===event.source){const muted=!!data.value;shell.dataset.muted=muted?'1':'0';const btn=shell._soundBtn||shell.closest('.modal-product-media')?.querySelector('.video-audio-btn');if(btn){btn.textContent=muted?'🔇':'🔊';btn.classList.toggle('is-sound-on',!muted);btn.setAttribute('aria-label',muted?'Activar sonido':'Silenciar video')}}})}catch(_){ }});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();